# Homework 0

### by Gianni Spiga

In [1]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [4]:
import numpy as np
import pandas as pd
from IPython.display import display
import copy

##  Question 1 
### a.)

In [2]:
u = np.array([1, 2, 3, 3, 2, 1]).T
# https://stackoverflow.com/questions/11885503/numpy-transpose-of-1d-array-not-giving-expected-result
u = u[None].T
#u

In [3]:
uuT = u @ u.T
#(2 / (u.T @ u))
U = np.identity(6) - (2 / (u.T @ u)) * uuT
U

array([[ 0.92857143, -0.14285714, -0.21428571, -0.21428571, -0.14285714,
        -0.07142857],
       [-0.14285714,  0.71428571, -0.42857143, -0.42857143, -0.28571429,
        -0.14285714],
       [-0.21428571, -0.42857143,  0.35714286, -0.64285714, -0.42857143,
        -0.21428571],
       [-0.21428571, -0.42857143, -0.64285714,  0.35714286, -0.42857143,
        -0.21428571],
       [-0.14285714, -0.28571429, -0.42857143, -0.42857143,  0.71428571,
        -0.14285714],
       [-0.07142857, -0.14285714, -0.21428571, -0.21428571, -0.14285714,
         0.92857143]])

### b.)

In [5]:
C = U @ U 
print(C)
# Duplicate data frame
C_copy = copy.deepcopy(C)
#print(C_copy)
# replace diagonal elements of copy with negative inf
np.fill_diagonal(C_copy, -np.inf)
# Find max and min value
max_value = C_copy.max()

# Replace -inf with +inf and find min
np.fill_diagonal(C_copy, np.inf)
min_value = C_copy.min()
print("The maximum value is ", max_value)
print("The minimum value is ", min_value)

[[ 1.00000000e+00 -3.29597460e-17 -3.98986399e-17 -5.37764278e-17
  -3.98986399e-17 -2.77555756e-17]
 [-3.29597460e-17  1.00000000e+00 -7.97972799e-17 -1.07552856e-16
  -5.20417043e-17 -2.77555756e-17]
 [-3.98986399e-17 -7.97972799e-17  1.00000000e+00 -5.55111512e-17
  -9.36750677e-17 -5.55111512e-17]
 [-5.37764278e-17 -1.07552856e-16 -5.55111512e-17  1.00000000e+00
  -1.49186219e-16 -8.32667268e-17]
 [-3.98986399e-17 -5.20417043e-17 -9.36750677e-17 -1.49186219e-16
   1.00000000e+00 -2.77555756e-17]
 [-2.77555756e-17 -2.77555756e-17 -5.55111512e-17 -8.32667268e-17
  -2.77555756e-17  1.00000000e+00]]
The maximum value is  -2.7755575615628914e-17
The minimum value is  -1.491862189340054e-16


### c.)

In [6]:
min_diag = np.diag(C).min()
max_diag = np.diag(C).max()

print("The maximum value in the diagonal is ", max_diag)
print("The minimum value in the diagonal is ", min_diag)

The maximum value in the diagonal is  1.0
The minimum value in the diagonal is  1.0


<IPython.core.display.Javascript object>

### d.) 

In [7]:
U @ u

array([[-1.],
       [-2.],
       [-3.],
       [-3.],
       [-2.],
       [-1.]])

<IPython.core.display.Javascript object>

## e.)

In [10]:
# Summing columns of abs(U) and finding max row value
np.max(np.sum(np.abs(U), axis = 1))

2.2857142857142856

<IPython.core.display.Javascript object>

### f.) 

In [13]:
# Remember python indexing starts at 0, 3rd row = index 2
print(U[2,])

# We can round for simplicity
np.round(U[2,])

[-0.21428571 -0.42857143  0.35714286 -0.64285714 -0.42857143 -0.21428571]


array([-0., -0.,  0., -1., -0., -0.])

<IPython.core.display.Javascript object>

### g.)

In [ ]:
U[2:, 1]

array([-0.42857143, -0.42857143, -0.28571429, -0.14285714])

<IPython.core.display.Javascript object>

### h.)

In [17]:
A = U[:,0:3]
P = np.round(A @ A.T, 3)
P

array([[ 0.929, -0.143, -0.214, -0.   , -0.   , -0.   ],
       [-0.143,  0.714, -0.429, -0.   , -0.   , -0.   ],
       [-0.214, -0.429,  0.357, -0.   , -0.   , -0.   ],
       [-0.   , -0.   , -0.   ,  0.643,  0.429,  0.214],
       [-0.   , -0.   , -0.   ,  0.429,  0.286,  0.143],
       [-0.   , -0.   , -0.   ,  0.214,  0.143,  0.071]])

<IPython.core.display.Javascript object>

### e.) 

In [25]:
np.max(np.sum(np.abs(np.round(P@P - P,3)), axis = 1))
#print(P@P - P)

0.0

<IPython.core.display.Javascript object>

### j.) 

In [27]:
B = U[:,3:]
Q = np.round(B @ B.T,3)
Q

array([[ 0.071,  0.143,  0.214, -0.   , -0.   , -0.   ],
       [ 0.143,  0.286,  0.429, -0.   , -0.   , -0.   ],
       [ 0.214,  0.429,  0.643, -0.   , -0.   , -0.   ],
       [-0.   , -0.   , -0.   ,  0.357, -0.429, -0.214],
       [-0.   , -0.   , -0.   , -0.429,  0.714, -0.143],
       [-0.   , -0.   , -0.   , -0.214, -0.143,  0.929]])

<IPython.core.display.Javascript object>

### k.) 

In [28]:
np.max(np.sum(np.abs(np.round(Q@Q - Q,3)), axis = 1))

0.0

<IPython.core.display.Javascript object>

### l.)

In [29]:
P + Q

array([[ 1.,  0.,  0., -0., -0., -0.],
       [ 0.,  1.,  0., -0., -0., -0.],
       [ 0.,  0.,  1., -0., -0., -0.],
       [-0., -0., -0.,  1.,  0.,  0.],
       [-0., -0., -0.,  0.,  1.,  0.],
       [-0., -0., -0.,  0.,  0.,  1.]])

<IPython.core.display.Javascript object>

## Question 2

In [48]:
oring = pd.read_csv("../STA208/hw0/oringp.dat",sep = "\s+", header = None)
display(oring)
# remove the last observation
oring = oring[:-1]
#display(oring)

# Find the correlation between number of fails ('0') and temperature ("66")
oring.iloc[:,3].corr(oring.iloc[:,4])

0         1  2    3   4
0      1   4/12/81  6  0.0  66
1      2  11/12/81  6  1.0  70
2      3   3/22/82  6  0.0  69
3      5  11/11/82  6  0.0  68
4      6   4/04/83  6  0.0  67
5      7   6/18/83  6  0.0  72
6      8   8/30/83  6  0.0  73
7      9  11/28/83  6  0.0  70
8   41-B   2/03/84  6  1.0  57
9   41-C   4/06/84  6  1.0  63
10  41-D   8/30/84  6  1.0  70
11  41-G  10/05/84  6  0.0  78
12  51-A  11/08/84  6  0.0  67
13  51-C   1/24/85  6  3.0  53
14  51-D   4/12/85  6  0.0  67
15  51-B   4/29/85  6  0.0  75
16  51-G   6/17/85  6  0.0  70
17  51-F   7/29/85  6  0.0  81
18  51-I   8/27/85  6  0.0  76
19  51-J  10/03/85  6  0.0  79
20  61-A  10/30/85  6  2.0  75
21  61-B  11/26/85  6  0.0  76
22  61-C   1/12/86  6  1.0  58
23  61-I   1/28/86  6  NaN  31

-0.5613284258418356

<IPython.core.display.Javascript object>

## Question 3

In [48]:
def dmvnorm_lowrank(y, mu, Z, sigma0, sigma1, log = False):
    if isinstance(mu, np.ndarray):
        n <- mu.size
    else:
        raise ValueError("mu should be a list")
    
    if (len(y) != n): 
        raise ValueError("y should have correct length")
    if sigma0 <0 or sigma1 < 0:
        raise ValueError("sigma should be positive")
    
    sZ = sigma1** 2 *Z @ Z.T + sigma0 ** 2 * np.identity(n = n)
    likhood = (-n/2 * np.log(2 * np.pi)) - (1/2 * np.log(np.linalg.det(sZ))) - (1/2*(y - mu).T @ np.linalg.inv(sZ) @ (y - mu))

    if log == False:
        return np.exp(likhood)
    else:
        return likhood

In [47]:
np.random.seed(123)

n = 10
q = 15

sigma0 = np.random.uniform(0, 10, size = 1)
sigma1 = np.random.uniform(0,10,size = 1)

Z = np.random.normal(10, size =  (n, q))

mu = np.random.rand(n,)
var_y = sigma1**2 * Z @ Z.T + sigma0**2 * np.identity(n)
y = np.random.multivariate_normal(mean = mu, cov = var_y) #mu + Z @ gamma + sigma0 * np.random.normal(size = n)

print(dmvnorm_lowrank(y = y, mu = mu, Z = Z, sigma0 = sigma0, sigma1 = sigma1, log= False))

from scipy.stats import multivariate_normal as mvn 
print(mvn.pdf(y, mean = mu, cov = var_y), "is scipy result")

9.20558563780895e-19
9.205585637808754e-19 is scipy result
