# Homework 0

In [102]:
%load_ext nb_black

The nb_black extension is already loaded. To reload it, use:
  %reload_ext nb_black


<IPython.core.display.Javascript object>

In [103]:
import numpy as np
import pandas as pd
import copy

<IPython.core.display.Javascript object>

##  Question 1 
### a.)

In [104]:
u = np.array([1, 2, 3, 3, 2, 1]).T
# https://stackoverflow.com/questions/11885503/numpy-transpose-of-1d-array-not-giving-expected-result
u = u[None].T
#u

<IPython.core.display.Javascript object>

In [105]:
uuT = u @ u.T
(2 / (u.T @ u))
U = np.identity(6) - (2 / (u.T @ u)) * uuT
U

array([[ 0.92857143, -0.14285714, -0.21428571, -0.21428571, -0.14285714,
        -0.07142857],
       [-0.14285714,  0.71428571, -0.42857143, -0.42857143, -0.28571429,
        -0.14285714],
       [-0.21428571, -0.42857143,  0.35714286, -0.64285714, -0.42857143,
        -0.21428571],
       [-0.21428571, -0.42857143, -0.64285714,  0.35714286, -0.42857143,
        -0.21428571],
       [-0.14285714, -0.28571429, -0.42857143, -0.42857143,  0.71428571,
        -0.14285714],
       [-0.07142857, -0.14285714, -0.21428571, -0.21428571, -0.14285714,
         0.92857143]])

<IPython.core.display.Javascript object>

### b.)

In [106]:
C = U @ U 
# Duplicate data frame
C_copy = copy.deepcopy(C)
#print(C_copy)
# replace diagonal elements of copy with negative inf
np.fill_diagonal(C_copy, -np.inf)
# Find max and min value
max_value = C_copy.max()

# Replace -inf with +inf and find min
np.fill_diagonal(C_copy, np.inf)
min_value = C_copy.min()
print("The maximum value is ", max_value)
print("The minimum value is ", min_value)

The maximum value is  -2.7755575615628914e-17
The minimum value is  -1.491862189340054e-16


<IPython.core.display.Javascript object>

### c.)

In [107]:
min_diag = np.diag(C).min()
max_diag = np.diag(C).max()

print("The maximum value in the diagonal is ", max_diag)
print("The minimum value in the diagonal is ", min_diag)

The maximum value in the diagonal is  1.0
The minimum value in the diagonal is  1.0


<IPython.core.display.Javascript object>

### d.) 

In [108]:
U @ u

array([[-1.],
       [-2.],
       [-3.],
       [-3.],
       [-2.],
       [-1.]])

<IPython.core.display.Javascript object>

## e.)

In [119]:
# Finding maximum in each column 
np.amax(np.abs(U), axis = 0)

array([0.92857143, 0.71428571, 0.64285714, 0.64285714, 0.71428571,
       0.92857143])

<IPython.core.display.Javascript object>

### f.) 

In [110]:
# Remember python indexing starts at 0, 3rd row = index 2
U[2,]

array([-0.21428571, -0.42857143,  0.35714286, -0.64285714, -0.42857143,
       -0.21428571])

<IPython.core.display.Javascript object>

### g.)

In [111]:
U[2:, 1]

array([-0.42857143, -0.42857143, -0.28571429, -0.14285714])

<IPython.core.display.Javascript object>

### h.)

In [118]:
A = U[:,0:3]
P = A @ A.T
P

array([[ 9.28571429e-01, -1.42857143e-01, -2.14285714e-01,
        -2.77555756e-17, -2.77555756e-17, -1.38777878e-17],
       [-1.42857143e-01,  7.14285714e-01, -4.28571429e-01,
        -5.55111512e-17, -2.77555756e-17, -1.38777878e-17],
       [-2.14285714e-01, -4.28571429e-01,  3.57142857e-01,
        -2.77555756e-17, -5.55111512e-17, -2.77555756e-17],
       [-2.77555756e-17, -5.55111512e-17, -2.77555756e-17,
         6.42857143e-01,  4.28571429e-01,  2.14285714e-01],
       [-2.77555756e-17, -2.77555756e-17, -5.55111512e-17,
         4.28571429e-01,  2.85714286e-01,  1.42857143e-01],
       [-1.38777878e-17, -1.38777878e-17, -2.77555756e-17,
         2.14285714e-01,  1.42857143e-01,  7.14285714e-02]])

<IPython.core.display.Javascript object>

### e.) 

In [122]:
np.amax(np.abs(P@P - P), axis = 0)
#print(P@P - P)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.68515995e-17
  -3.96508223e-18 -1.98254112e-18]
 [ 0.00000000e+00  1.11022302e-16  0.00000000e+00 -1.88341406e-17
   1.98254112e-18  9.91270558e-19]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.23259516e-32
   2.18079523e-17  1.09039761e-17]
 [-1.68515995e-17 -1.88341406e-17  1.23259516e-32 -1.11022302e-16
  -5.55111512e-17 -2.77555756e-17]
 [-3.96508223e-18  1.98254112e-18  2.18079523e-17 -5.55111512e-17
  -5.55111512e-17 -2.77555756e-17]
 [-1.98254112e-18  9.91270558e-19  1.09039761e-17 -2.77555756e-17
  -2.77555756e-17 -1.38777878e-17]]


<IPython.core.display.Javascript object>

### j.) 

In [127]:
B = U[:,3:]
Q = B @ B.T
Q

array([[ 7.14285714e-02,  1.42857143e-01,  2.14285714e-01,
        -2.60208521e-17, -1.21430643e-17, -1.38777878e-17],
       [ 1.42857143e-01,  2.85714286e-01,  4.28571429e-01,
        -5.20417043e-17, -2.42861287e-17, -2.77555756e-17],
       [ 2.14285714e-01,  4.28571429e-01,  6.42857143e-01,
        -2.77555756e-17, -3.81639165e-17, -2.77555756e-17],
       [-2.60208521e-17, -5.20417043e-17, -2.77555756e-17,
         3.57142857e-01, -4.28571429e-01, -2.14285714e-01],
       [-1.21430643e-17, -2.42861287e-17, -3.81639165e-17,
        -4.28571429e-01,  7.14285714e-01, -1.42857143e-01],
       [-1.38777878e-17, -2.77555756e-17, -2.77555756e-17,
        -2.14285714e-01, -1.42857143e-01,  9.28571429e-01]])

<IPython.core.display.Javascript object>

### k.) 

In [128]:
np.amax(np.abs(Q@Q - Q), axis = 0)

array([2.77555756e-17, 5.55111512e-17, 1.11022302e-16, 5.55111512e-17,
       1.11022302e-16, 2.77555756e-17])

<IPython.core.display.Javascript object>

### l.)

In [129]:
P + Q

array([[ 1.00000000e+00, -2.77555756e-17, -5.55111512e-17,
        -5.37764278e-17, -3.98986399e-17, -2.77555756e-17],
       [-2.77555756e-17,  1.00000000e+00, -1.11022302e-16,
        -1.07552856e-16, -5.20417043e-17, -4.16333634e-17],
       [-5.55111512e-17, -1.11022302e-16,  1.00000000e+00,
        -5.55111512e-17, -9.36750677e-17, -5.55111512e-17],
       [-5.37764278e-17, -1.07552856e-16, -5.55111512e-17,
         1.00000000e+00, -1.66533454e-16, -5.55111512e-17],
       [-3.98986399e-17, -5.20417043e-17, -9.36750677e-17,
        -1.66533454e-16,  1.00000000e+00, -2.77555756e-17],
       [-2.77555756e-17, -4.16333634e-17, -5.55111512e-17,
        -5.55111512e-17, -2.77555756e-17,  1.00000000e+00]])

<IPython.core.display.Javascript object>